name: Publish to GitHub Package Registry

on:
    release:
        types: [created]

jobs:
    publish-gpr:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Clear npm configuration
              run: npm config delete registry

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 14 # Adjust the Node.js version as needed
                  registry-url: https://npm.pkg.github.com/

            - name: Install dependencies
              run: npm ci

            - name: Build
              run: npm run build

            - name: Publish to GitHub Package Registry
              run: npm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
